name       : i3lock
version    : 2.10.1
release    : 7
source     :
    - git|https://github.com/PandorasFox/i3lock-color.git : 2.10.1c
license    : BSD-3-Clause
component  : desktop.i3
summary    : i3lock is a simple screen locker like slock (using PandorasFox's color fork for improved customization)
description: |
    i3lock is a simple screen locker like slock (using PandorasFox's color fork for improved customization)
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - libev-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
