name       : i3lock
version    : 2.7
release    : 3
source     :
    - https://github.com/chrjguill/i3lock-color/archive/2.7.tar.gz : 8483a12d120c1349185fd811b9bf6e73c222ab586a0faef337bd871c6f9aa8f1
license    : BSD-3-Clause
component  : desktop.i3
summary    : i3lock is a simple screen locker like slock.
description: |
    i3lock is a simple screen locker like slock.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - libev-devel
build      : |
    %make
install    : |
    %make_install
