name       : i3lock
version    : 2.8
release    : 2
source     :
    - https://i3wm.org/i3lock/i3lock-2.8.tar.bz2 : 028fc0f74df10826514d5a4ed38f6895935d1f5d47ca9fcffc64b076aaf6e2f4
license    : BSD-3-Clause
component  : desktop.i3
summary    : i3lock is a simple screen locker like slock.
description: |
    i3lock is a simple screen locker like slock.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - libev-devel
build      : |
    %make
install    : |
    %make_install
