name       : i3lock
version    : 2.14.1
release    : 16
source     :
    - https://github.com/i3/i3lock/archive/2.14.1.tar.gz : af7711676057eece3ed0829ebf1b7a0681a5a34cd3677e63afa2ef0e2335b0c0
license    : BSD-3-Clause
component  : desktop.i3
summary    : i3lock is a simple screen locker like slock.
description: |
    i3lock is a simple screen locker like slock.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - libev-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc
