name       : i3lock
version    : '2.9'
release    : 4
source     :
    - https://github.com/i3/i3lock/archive/2.9.tar.gz : c0d5fbf136aeec6677eb18bbffcac1e228d21f137e57609a2775c245caf9aea3
license    : BSD-3-Clause
component  : desktop.i3
summary    : i3lock is a simple screen locker like slock.
description: |
    i3lock is a simple screen locker like slock.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - libev-devel
build      : |
    %make
install    : |
    %make_install
